-- Creación de usuario
CREATE USER FIDE_SAMDESIGN IDENTIFIED BY SAMDESIGN;

GRANT CONNECT TO FIDE_SAMDESIGN;
GRANT DBA TO FIDE_SAMDESIGN;
GRANT RESOURCE TO FIDE_SAMDESIGN;

-- 1
CREATE TABLE FIDE_SAMDESIGN.FIDE_Users_TB (
    PK_User_ID NUMBER CONSTRAINT FIDE_PK_USER_ID PRIMARY KEY,
    User_Name VARCHAR2(100),
    User_Email VARCHAR2(100) CONSTRAINT FIDE_USER_EMAIL_NN NOT NULL,
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 2
CREATE TABLE FIDE_SAMDESIGN.FIDE_Vendor_TB (
    Vendor_ID NUMBER CONSTRAINT FIDE_PK_VENDOR_ID PRIMARY KEY,
    Vendor_Name VARCHAR2(100),
    Vendor_Address_ID NUMBER,
    Vendor_eMail VARCHAR2(100) CONSTRAINT FIDE_VENDOR_EMAIL_NN NOT NULL,
    Vendor_Balance FLOAT,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Status_ID NUMBER,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 3
CREATE TABLE FIDE_SAMDESIGN.FIDE_Employee_TB (
    Employee_ID NUMBER CONSTRAINT FIDE_PK_EMPLOYEE_ID PRIMARY KEY,
    Employee_Name VARCHAR2(100),
    Employee_LastName1 VARCHAR2(100),
    Employee_LastName2 VARCHAR2(100),
    Employee_eMail VARCHAR2(100),
    Employee_Position VARCHAR2(100),
    Employee_Salary FLOAT,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Status_ID NUMBER,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 4
CREATE TABLE FIDE_SAMDESIGN.FIDE_Status_TB (
    Status_ID NUMBER CONSTRAINT FIDE_PK_STATUS_ID PRIMARY KEY,
    Description VARCHAR2(255),
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP
);

-- 5
CREATE TABLE FIDE_SAMDESIGN.FIDE_Special_Order_TB (
    Order_ID NUMBER CONSTRAINT FIDE_PK_ORDER_ID PRIMARY KEY,
    Customer_ID NUMBER,
    Order_Date TIMESTAMP,
    Order_Qty NUMBER,
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Customer_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Customer_TB(Customer_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 6
CREATE TABLE FIDE_SAMDESIGN.FIDE_Customer_TB (
    Customer_ID NUMBER CONSTRAINT FIDE_PK_CUSTOMER_ID PRIMARY KEY,
    Customer_Name VARCHAR2(100),
    Customer_Email VARCHAR2(100),
    Customer_Phone_number VARCHAR2(50),
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 7
CREATE TABLE FIDE_SAMDESIGN.FIDE_Category_Type_TB (
    Category_ID NUMBER CONSTRAINT FIDE_PK_CATEGORY_ID PRIMARY KEY,
    Description VARCHAR2(255),
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 8
CREATE TABLE FIDE_SAMDESIGN.FIDE_Inventory_TB (
    Inventory_ID NUMBER CONSTRAINT FIDE_PK_INVENTORY_ID PRIMARY KEY,
    Product_ID NUMBER,
    Comments VARCHAR2(255),
    Quantity_Stock NUMBER,
    Quantity_Reserved NUMBER,
    Quantity_Threshold NUMBER,
    Status_ID NUMBER,
    Last_Restock TIMESTAMP,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID),
    FOREIGN KEY (Product_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Product_TB(Product_ID)
);

-- 9
CREATE TABLE FIDE_SAMDESIGN.FIDE_Billing_TB (
    Billing_ID NUMBER CONSTRAINT FIDE_PK_BILLING_ID PRIMARY KEY,
    Order_ID NUMBER,
    Customer_ID NUMBER,
    Invoiced_Address_ID NUMBER,
    Billing_Date TIMESTAMP,
    Total_Amount NUMBER,
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Payment_Method_ID NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Order_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Order_TB(Order_ID),
    FOREIGN KEY (Customer_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Customer_TB(Customer_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID),
    FOREIGN KEY (Payment_Method_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Payment_Method_TB(Payment_Method_ID)
);

-- 10
CREATE TABLE FIDE_SAMDESIGN.FIDE_Product_TB (
    Product_ID NUMBER CONSTRAINT FIDE_PK_PRODUCT_ID PRIMARY KEY,
    Description VARCHAR2(255),
    Category_Type_ID NUMBER,
    Comments VARCHAR2(255),
    Unit_price NUMBER,
    Quantity_OnHand NUMBER,
    Quantity_Lend NUMBER,
    Total_Qty NUMBER,
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On DATE,
    Modified_By VARCHAR2(50),
    Modified_On DATE,
    FOREIGN KEY (Category_Type_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Category_Type_TB(Category_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 11
CREATE TABLE FIDE_SAMDESIGN.FIDE_Payment_Method_TB (
    Payment_Method_ID NUMBER CONSTRAINT FIDE_PK_PAYMENT_METHOD_ID PRIMARY KEY,
    Payment_Method_Name VARCHAR2(255),
    Description VARCHAR2(255),
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 12
CREATE TABLE FIDE_SAMDESIGN.FIDE_Cart_TB (
    Cart_ID NUMBER CONSTRAINT FIDE_PK_CART_ID PRIMARY KEY,
    Customer_ID NUMBER,
    Address_ID NUMBER,
    Order_Date TIMESTAMP,
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Payment_Method_ID NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Customer_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Customer_TB(Customer_ID),
    FOREIGN KEY (Address_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Address_TB(Address_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID),
    FOREIGN KEY (Payment_Method_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Payment_Method_TB(Payment_Method_ID)
);

-- 13
CREATE TABLE FIDE_SAMDESIGN.FIDE_Cart_Lines_TB (
    Cart_Line_ID NUMBER CONSTRAINT FIDE_PK_CART_LINE_ID PRIMARY KEY,
    Cart_ID NUMBER,
    Product_ID NUMBER,
    Qty_Item NUMBER,
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Total_Price NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Cart_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Cart_TB(Cart_ID),
    FOREIGN KEY (Product_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Product_TB(Product_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 14
CREATE TABLE FIDE_SAMDESIGN.FIDE_Order_TB (
    Order_ID NUMBER CONSTRAINT FIDE_PK_ORDER_ID PRIMARY KEY,
    Customer_ID NUMBER,
    Order_Date TIMESTAMP,
    Order_Amount NUMBER,
    Order_Tax NUMBER,
    Comments VARCHAR2(255),
    Dispatch BOOLEAN,
    Fullfield BOOLEAN,
    Status_ID NUMBER,
    Payment_Method_ID NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Customer_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Customer_TB(Customer_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID),
    FOREIGN KEY (Payment_Method_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Payment_Method_TB(Payment_Method_ID)
);

-- 15
CREATE TABLE FIDE_SAMDESIGN.FIDE_Order_Lines_TB (
    Order_Line_ID NUMBER CONSTRAINT FIDE_PK_ORDER_LINE_ID PRIMARY KEY,
    Order_ID NUMBER,
    Product_ID NUMBER,
    Qty_Item NUMBER,
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Total_Price NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Order_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Order_TB(Order_ID),
    FOREIGN KEY (Product_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Product_TB(Product_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 16
CREATE TABLE FIDE_SAMDESIGN.FIDE_City_Address_TB (
    City_ID NUMBER CONSTRAINT FIDE_PK_CITY_ID PRIMARY KEY,
    Name VARCHAR2(255),
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 17
CREATE TABLE FIDE_SAMDESIGN.FIDE_Countries_TB (
    Country_ID NUMBER CONSTRAINT FIDE_PK_COUNTRY_ID PRIMARY KEY,
    Name VARCHAR2(255),
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 18
CREATE TABLE FIDE_SAMDESIGN.FIDE_State_Address_TB (
    State_ID NUMBER CONSTRAINT FIDE_PK_STATE_ID PRIMARY KEY,
    Name VARCHAR2(255),
    Status_ID NUMBER,
    Created_By VARCHAR2(50),
    Created_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID)
);

-- 19
CREATE TABLE FIDE_SAMDESIGN.FIDE_Billing_TB (
    Billing_ID NUMBER CONSTRAINT FIDE_PK_BILLING_ID PRIMARY KEY,
    Order_ID NUMBER,
    Customer_ID NUMBER,
    Invoiced_Address_ID NUMBER,
    Billing_Date TIMESTAMP,
    Total_Amount NUMBER,
    Comments VARCHAR2(255),
    Status_ID NUMBER,
    Payment_Method_ID NUMBER,
    Created_On TIMESTAMP,
    Created_By VARCHAR2(50),
    Modified_On TIMESTAMP,
    Modified_By VARCHAR2(50),
    FOREIGN KEY (Order_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Order_TB(Order_ID),
    FOREIGN KEY (Customer_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Customer_TB(Customer_ID),
    FOREIGN KEY (Status_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Status_TB(Status_ID),
    FOREIGN KEY (Payment_Method_ID) REFERENCES FIDE_SAMDESIGN.FIDE_Payment_Method_TB(Payment_Method_ID)
);
