-- Procedimiento para insertar STATUS registros
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_STATUS_TB_SP
(
    P_STATUS_ID    IN NUMBER,
    P_DESCRIPTION  IN VARCHAR2,
    P_CREATED_BY   IN VARCHAR2,
    P_CREATED_ON   IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_STATUS_TB(Status_ID, Description, Created_By, Created_On)
    VALUES (P_STATUS_ID, P_DESCRIPTION, P_CREATED_BY, P_CREATED_ON);
    COMMIT;
END INSERTAR_FIDE_STATUS_TB_SP;

-- Procedimiento para modificar STATUS registros
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_STATUS_TB_SP
(
    P_STATUS_ID    IN NUMBER,
    P_DESCRIPTION  IN VARCHAR2,
    P_MODIFIED_BY  IN VARCHAR2,
    P_MODIFIED_ON  IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_STATUS_TB
    SET Description = P_DESCRIPTION,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Status_ID = P_STATUS_ID;
    COMMIT;
END MODIFICAR_FIDE_STATUS_TB_SP;

-- Procedimiento para eliminar STATUS registros
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_STATUS_TB_SP
(
    P_STATUS_ID IN NUMBER
)
IS
BEGIN
    DELETE FROM FIDE_SAMDESIGN.FIDE_STATUS_TB WHERE Status_ID = P_STATUS_ID;
    COMMIT;
END ELIMINAR_FIDE_STATUS_TB_SP;


-- Procedimiento para insertar ROL registros
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_ROL_TB_SP
(
    P_ROL_ID      IN NUMBER,
    P_ROL_NAME    IN VARCHAR2,
    P_STATUS_ID   IN NUMBER,
    P_CREATED_BY  IN VARCHAR2,
    P_CREATED_ON  IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_ROL_TB(rol_id, rol_name, Status_ID, Created_By, Created_On)
    VALUES (P_ROL_ID, P_ROL_NAME, P_STATUS_ID, P_CREATED_BY, P_CREATED_ON);
    COMMIT;
END INSERTAR_FIDE_ROL_TB_SP;

-- Procedimiento para modificar ROL registros
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_ROL_TB_SP
(
    P_ROL_ID      IN NUMBER,
    P_ROL_NAME    IN VARCHAR2,
    P_STATUS_ID   IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ROL_TB
    SET rol_name    = P_ROL_NAME,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE rol_id = P_ROL_ID;
    COMMIT;
END MODIFICAR_FIDE_ROL_TB_SP;

-- Procedimiento para eliminar ROL registros
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_ROL_TB_SP
(
    P_ROL_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ROL_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE rol_id = P_ROL_ID;
    COMMIT;
END ELIMINAR_FIDE_ROL_TB_SP;

-- Procedimiento para insertar USERS
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_USERS_TB_SP
(
    P_USER_ID     IN NUMBER,
    P_USER_NAME   IN VARCHAR2,
    P_USER_EMAIL  IN VARCHAR2,
    P_PASSWORD    IN VARCHAR2,
    P_ROL_ID      IN NUMBER,
    P_STATUS_ID   IN NUMBER,
    P_CREATED_BY  IN VARCHAR2,
    P_CREATED_ON  IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_USERS_TB(User_ID, User_Name, User_Email, Password, Rol_ID, Status_ID, Created_By, Created_On)
    VALUES (P_USER_ID, P_USER_NAME, P_USER_EMAIL, P_PASSWORD, P_ROL_ID, P_STATUS_ID, P_CREATED_BY, P_CREATED_ON);
    COMMIT;
END INSERTAR_FIDE_USERS_TB_SP;

-- Procedimiento para modificar USERS
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_USERS_TB_SP
(
    P_USER_ID     IN NUMBER,
    P_USER_NAME   IN VARCHAR2,
    P_USER_EMAIL  IN VARCHAR2,
    P_PASSWORD    IN VARCHAR2,
    P_ROL_ID      IN NUMBER,
    P_STATUS_ID   IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_USERS_TB
    SET User_Name   = P_USER_NAME,
        User_Email  = P_USER_EMAIL,
        Password    = P_PASSWORD,
        Rol_ID      = P_ROL_ID,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE User_ID = P_USER_ID;
    COMMIT;
END MODIFICAR_FIDE_USERS_TB_SP;

-- Procedimiento para desactivar USERS
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_USERS_TB_SP
(
    P_USER_ID     IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_USERS_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE User_ID = P_USER_ID;
    COMMIT;
END ELIMINAR_FIDE_USERS_TB_SP;

-- Procedimiento para insertar CATEGORY
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_CATEGORY_TYPE_TB_SP
(
    P_CATEGORY_ID IN NUMBER,
    P_DESCRIPTION IN VARCHAR2,
    P_COMMENTS    IN VARCHAR2,
    P_STATUS_ID   IN NUMBER,
    P_CREATED_BY  IN VARCHAR2,
    P_CREATED_ON  IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_CATEGORY_TYPE_TB(Category_ID, Description, Comments, Status_ID, Created_By, Created_On)
    VALUES (P_CATEGORY_ID, P_DESCRIPTION, P_COMMENTS, P_STATUS_ID, P_CREATED_BY, P_CREATED_ON);
    COMMIT;
END INSERTAR_FIDE_CATEGORY_TYPE_TB_SP;

-- Procedimiento para modificar CATEGORY
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_CATEGORY_TYPE_TB_SP
(
    P_CATEGORY_ID IN NUMBER,
    P_DESCRIPTION IN VARCHAR2,
    P_COMMENTS    IN VARCHAR2,
    P_STATUS_ID   IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CATEGORY_TYPE_TB
    SET Description = P_DESCRIPTION,
        Comments    = P_COMMENTS,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Category_ID = P_CATEGORY_ID;
    COMMIT;
END MODIFICAR_FIDE_CATEGORY_TYPE_TB_SP;

-- Procedimiento para desactivar CATEGORY 
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_CATEGORY_TYPE_TB_SP
(
    P_CATEGORY_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CATEGORY_TYPE_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Category_ID = P_CATEGORY_ID;
    COMMIT;
END ELIMINAR_FIDE_CATEGORY_TYPE_TB_SP;

-- Procedimiento para insertar VENDOR
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_VENDOR_TB_SP
(
    P_VENDOR_ID         IN NUMBER,
    P_VENDOR_NAME       IN VARCHAR2,
    P_VENDOR_ADDRESS_ID IN NUMBER,
    P_VENDOR_EMAIL      IN VARCHAR2,
    P_VENDOR_BALANCE    IN FLOAT,
    P_CREATED_BY        IN VARCHAR2,
    P_CREATED_ON        IN TIMESTAMP,
    P_STATUS_ID         IN NUMBER
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_VENDOR_TB(Vendor_ID, Vendor_Name, Vendor_Address_ID, Vendor_eMail, Vendor_Balance, Created_By, Created_On, Status_ID)
    VALUES (P_VENDOR_ID, P_VENDOR_NAME, P_VENDOR_ADDRESS_ID, P_VENDOR_EMAIL, P_VENDOR_BALANCE, P_CREATED_BY, P_CREATED_ON, P_STATUS_ID);
    COMMIT;
END INSERTAR_FIDE_VENDOR_TB_SP;

-- Procedimiento para modificar VENDOR
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_VENDOR_TB_SP
(
    P_VENDOR_ID         IN NUMBER,
    P_VENDOR_NAME       IN VARCHAR2,
    P_VENDOR_ADDRESS_ID IN NUMBER,
    P_VENDOR_EMAIL      IN VARCHAR2,
    P_VENDOR_BALANCE    IN FLOAT,
    P_STATUS_ID         IN NUMBER,
    P_MODIFIED_BY       IN VARCHAR2,
    P_MODIFIED_ON       IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_VENDOR_TB
    SET Vendor_Name        = P_VENDOR_NAME,
        Vendor_Address_ID  = P_VENDOR_ADDRESS_ID,
        Vendor_eMail       = P_VENDOR_EMAIL,
        Vendor_Balance     = P_VENDOR_BALANCE,
        Status_ID          = P_STATUS_ID,
        Modified_By        = P_MODIFIED_BY,
        Modified_On        = P_MODIFIED_ON
    WHERE Vendor_ID = P_VENDOR_ID;
    COMMIT;
END MODIFICAR_FIDE_VENDOR_TB_SP;

-- Procedimiento para desactivar VENDOR
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_VENDOR_TB_SP
(
    P_VENDOR_ID   IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_VENDOR_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Vendor_ID = P_VENDOR_ID;
    COMMIT;
END ELIMINAR_FIDE_VENDOR_TB_SP;

--  Procedimiento para insertar EMPLOYEE
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_EMPLOYEE_TB_SP
(
    P_EMPLOYEE_ID         IN NUMBER,
    P_EMPLOYEE_NAME       IN VARCHAR2,
    P_EMPLOYEE_LASTNAME1  IN VARCHAR2,
    P_EMPLOYEE_LASTNAME2  IN VARCHAR2,
    P_EMPLOYEE_EMAIL      IN VARCHAR2,
    P_EMPLOYEE_POSITION   IN VARCHAR2,
    P_EMPLOYEE_SALARY     IN FLOAT,
    P_CREATED_BY          IN VARCHAR2,
    P_CREATED_ON          IN TIMESTAMP,
    P_STATUS_ID           IN NUMBER
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_EMPLOYEE_TB
    (
        Employee_ID,
        Employee_Name,
        Employee_LastName1,
        Employee_LastName2,
        Employee_eMail,
        Employee_Position,
        Employee_Salary,
        Created_By,
        Created_On,
        Status_ID
    )
    VALUES
    (
        P_EMPLOYEE_ID,
        P_EMPLOYEE_NAME,
        P_EMPLOYEE_LASTNAME1,
        P_EMPLOYEE_LASTNAME2,
        P_EMPLOYEE_EMAIL,
        P_EMPLOYEE_POSITION,
        P_EMPLOYEE_SALARY,
        P_CREATED_BY,
        P_CREATED_ON,
        P_STATUS_ID
    );
    COMMIT;
END INSERTAR_FIDE_EMPLOYEE_TB_SP;

--Procedimiento para modificar EMPLOYEE
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_EMPLOYEE_TB_SP
(
    P_EMPLOYEE_ID         IN NUMBER,
    P_EMPLOYEE_NAME       IN VARCHAR2,
    P_EMPLOYEE_LASTNAME1  IN VARCHAR2,
    P_EMPLOYEE_LASTNAME2  IN VARCHAR2,
    P_EMPLOYEE_EMAIL      IN VARCHAR2,
    P_EMPLOYEE_POSITION   IN VARCHAR2,
    P_EMPLOYEE_SALARY     IN FLOAT,
    P_MODIFIED_BY         IN VARCHAR2,
    P_MODIFIED_ON         IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_EMPLOYEE_TB
    SET Employee_Name       = P_EMPLOYEE_NAME,
        Employee_LastName1  = P_EMPLOYEE_LASTNAME1,
        Employee_LastName2  = P_EMPLOYEE_LASTNAME2,
        Employee_eMail      = P_EMPLOYEE_EMAIL,
        Employee_Position   = P_EMPLOYEE_POSITION,
        Employee_Salary     = P_EMPLOYEE_SALARY,
        Modified_By         = P_MODIFIED_BY,
        Modified_On         = P_MODIFIED_ON
    WHERE Employee_ID = P_EMPLOYEE_ID;
    COMMIT;
END MODIFICAR_FIDE_EMPLOYEE_TB_SP;
/
-- Procedimiento para desactivar EMPLOYEE
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_EMPLOYEE_TB_SP
(
    P_EMPLOYEE_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_EMPLOYEE_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Employee_ID = P_EMPLOYEE_ID;
    COMMIT;
END ELIMINAR_FIDE_EMPLOYEE_TB_SP;
/

-- Procedimiento para insertar PAYMENT_METHOD
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_PAYMENT_METHOD_TB_SP
(
    P_PAYMENT_METHOD_ID   IN NUMBER,
    P_PAYMENT_METHOD_NAME IN VARCHAR2,
    P_DESCRIPTION         IN VARCHAR2,
    P_STATUS_ID           IN NUMBER,
    P_CREATED_BY          IN VARCHAR2,
    P_CREATED_ON          IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_PAYMENT_METHOD_TB
    (
        Payment_Method_ID,
        Payment_Method_Name,
        Description,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_PAYMENT_METHOD_ID,
        P_PAYMENT_METHOD_NAME,
        P_DESCRIPTION,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_PAYMENT_METHOD_TB_SP;
/

-- Procedimiento para modificar PAYMENT_METHOD
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_PAYMENT_METHOD_TB_SP
(
    P_PAYMENT_METHOD_ID   IN NUMBER,
    P_PAYMENT_METHOD_NAME IN VARCHAR2,
    P_DESCRIPTION         IN VARCHAR2,
    P_STATUS_ID           IN NUMBER,
    P_MODIFIED_BY         IN VARCHAR2,
    P_MODIFIED_ON         IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_PAYMENT_METHOD_TB
    SET Payment_Method_Name = P_PAYMENT_METHOD_NAME,
        Description         = P_DESCRIPTION,
        Status_ID           = P_STATUS_ID,
        Modified_By         = P_MODIFIED_BY,
        Modified_On         = P_MODIFIED_ON
    WHERE Payment_Method_ID = P_PAYMENT_METHOD_ID;
    COMMIT;
END MODIFICAR_FIDE_PAYMENT_METHOD_TB_SP;
/

-- Procedimiento para desactivar PAYMENT_METHOD
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_PAYMENT_METHOD_TB_SP
(
    P_PAYMENT_METHOD_ID IN NUMBER,
    P_MODIFIED_BY       IN VARCHAR2,
    P_MODIFIED_ON       IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_PAYMENT_METHOD_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Payment_Method_ID = P_PAYMENT_METHOD_ID;
    COMMIT;
END ELIMINAR_FIDE_PAYMENT_METHOD_TB_SP;
/

-- Procedimiento para Insertar CITY_ADDRESS
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_CITY_ADDRESS_TB_SP
(
    P_CITY_ID    IN NUMBER,
    P_NAME       IN VARCHAR2,
    P_STATUS_ID  IN NUMBER,
    P_CREATED_BY IN VARCHAR2,
    P_CREATED_ON IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_CITY_ADDRESS_TB
    (
        City_ID,
        Name,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_CITY_ID,
        P_NAME,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_CITY_ADDRESS_TB_SP;
/

-- Procedimiento para Modificar CITY_ADDRESS
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_CITY_ADDRESS_TB_SP
(
    P_CITY_ID    IN NUMBER,
    P_NAME       IN VARCHAR2,
    P_STATUS_ID  IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CITY_ADDRESS_TB
    SET Name        = P_NAME,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE City_ID = P_CITY_ID;
    COMMIT;
END MODIFICAR_FIDE_CITY_ADDRESS_TB_SP;
/

-- Procedimiento para desactivar CITY_ADDRESS
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_CITY_ADDRESS_TB_SP
(
    P_CITY_ID    IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CITY_ADDRESS_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE City_ID = P_CITY_ID;
    COMMIT;
END ELIMINAR_FIDE_CITY_ADDRESS_TB_SP;
/

 

-- Procedimiento para Insertar COUNTRIES
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_COUNTRIES_TB_SP
(
    P_COUNTRY_ID IN NUMBER,
    P_NAME       IN VARCHAR2,
    P_STATUS_ID  IN NUMBER,
    P_CREATED_BY IN VARCHAR2,
    P_CREATED_ON IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_COUNTRIES_TB
    (
        Country_ID,
        Name,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_COUNTRY_ID,
        P_NAME,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_COUNTRIES_TB_SP;
/

-- Procedimiento para Modificar COUNTRIES
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_COUNTRIES_TB_SP
(
    P_COUNTRY_ID IN NUMBER,
    P_NAME       IN VARCHAR2,
    P_STATUS_ID  IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_COUNTRIES_TB
    SET Name        = P_NAME,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Country_ID = P_COUNTRY_ID;
    COMMIT;
END MODIFICAR_FIDE_COUNTRIES_TB_SP;
/

-- Procedimiento para desactivar COUNTRIES
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_COUNTRIES_TB_SP
(
    P_COUNTRY_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_COUNTRIES_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Country_ID = P_COUNTRY_ID;
    COMMIT;
END ELIMINAR_FIDE_COUNTRIES_TB_SP;
/

 

-- Procedimiento para Insertar STATE_ADDRESS
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_STATE_ADDRESS_TB_SP
(
    P_STATE_ID   IN NUMBER,
    P_NAME       IN VARCHAR2,
    P_STATUS_ID  IN NUMBER,
    P_CREATED_BY IN VARCHAR2,
    P_CREATED_ON IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_STATE_ADDRESS_TB
    (
        State_ID,
        Name,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_STATE_ID,
        P_NAME,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_STATE_ADDRESS_TB_SP;
/

-- Procedimiento para Modificar STATE_ADDRESS
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_STATE_ADDRESS_TB_SP
(
    P_STATE_ID   IN NUMBER,
    P_NAME       IN VARCHAR2,
    P_STATUS_ID  IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_STATE_ADDRESS_TB
    SET Name        = P_NAME,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE State_ID = P_STATE_ID;
    COMMIT;
END MODIFICAR_FIDE_STATE_ADDRESS_TB_SP;
/

-- Procedimiento para desactivar STATE_ADDRESS
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_STATE_ADDRESS_TB_SP
(
    P_STATE_ID   IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_STATE_ADDRESS_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE State_ID = P_STATE_ID;
    COMMIT;
END ELIMINAR_FIDE_STATE_ADDRESS_TB_SP;
/

 

-- Procedimiento para Insertar CUSTOMER
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_CUSTOMER_TB_SP
(
    P_CUSTOMER_ID           IN NUMBER,
    P_CUSTOMER_NAME         IN VARCHAR2,
    P_CUSTOMER_EMAIL        IN VARCHAR2,
    P_CUSTOMER_PHONE_NUMBER IN VARCHAR2,
    P_STATUS_ID             IN NUMBER,
    P_CREATED_BY            IN VARCHAR2,
    P_CREATED_ON            IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_CUSTOMER_TB
    (
        Customer_ID,
        Customer_Name,
        Customer_Email,
        Customer_Phone_number,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_CUSTOMER_ID,
        P_CUSTOMER_NAME,
        P_CUSTOMER_EMAIL,
        P_CUSTOMER_PHONE_NUMBER,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_CUSTOMER_TB_SP;
/

-- Procedimiento para Modificar CUSTOMER
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_CUSTOMER_TB_SP
(
    P_CUSTOMER_ID           IN NUMBER,
    P_CUSTOMER_NAME         IN VARCHAR2,
    P_CUSTOMER_EMAIL        IN VARCHAR2,
    P_CUSTOMER_PHONE_NUMBER IN VARCHAR2,
    P_STATUS_ID             IN NUMBER,
    P_MODIFIED_BY           IN VARCHAR2,
    P_MODIFIED_ON           IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CUSTOMER_TB
    SET Customer_Name         = P_CUSTOMER_NAME,
        Customer_Email        = P_CUSTOMER_EMAIL,
        Customer_Phone_number = P_CUSTOMER_PHONE_NUMBER,
        Status_ID             = P_STATUS_ID,
        Modified_By           = P_MODIFIED_BY,
        Modified_On           = P_MODIFIED_ON
    WHERE Customer_ID = P_CUSTOMER_ID;
    COMMIT;
END MODIFICAR_FIDE_CUSTOMER_TB_SP;
/

-- Procedimiento para desactivar CUSTOMER
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_CUSTOMER_TB_SP
(
    P_CUSTOMER_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CUSTOMER_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Customer_ID = P_CUSTOMER_ID;
    COMMIT;
END ELIMINAR_FIDE_CUSTOMER_TB_SP;
/

 

-- Procedimiento para Insertar ADDRESS
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_ADDRESS_TB_SP
(
    P_ADDRESS_ID   IN NUMBER,
    P_ADDRESS      IN VARCHAR2,
    P_ID_STATE     IN NUMBER,
    P_ID_CITY      IN NUMBER,
    P_ZIP_CODE     IN NUMBER,
    P_ID_COUNTRY   IN NUMBER,
    P_STATUS_ID    IN NUMBER,
    P_CREATED_BY   IN VARCHAR2,
    P_CREATED_ON   IN TIMESTAMP,
    P_ID_CUSTOMER  IN NUMBER
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_ADDRESS_TB
    (
        Address_ID,
        Address,
        ID_State,
        ID_City,
        ZIP_Code,
        ID_Country,
        Status_ID,
        Created_By,
        Created_On,
        ID_Customer
    )
    VALUES
    (
        P_ADDRESS_ID,
        P_ADDRESS,
        P_ID_STATE,
        P_ID_CITY,
        P_ZIP_CODE,
        P_ID_COUNTRY,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON,
        P_ID_CUSTOMER
    );
    COMMIT;
END INSERTAR_FIDE_ADDRESS_TB_SP;
/

-- Procedimiento para Modificar ADDRESS
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_ADDRESS_TB_SP
(
    P_ADDRESS_ID   IN NUMBER,
    P_ADDRESS      IN VARCHAR2,
    P_ID_STATE     IN NUMBER,
    P_ID_CITY      IN NUMBER,
    P_ZIP_CODE     IN NUMBER,
    P_ID_COUNTRY   IN NUMBER,
    P_STATUS_ID    IN NUMBER,
    P_MODIFIED_BY  IN VARCHAR2,
    P_MODIFIED_ON  IN TIMESTAMP,
    P_ID_CUSTOMER  IN NUMBER
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ADDRESS_TB
    SET Address     = P_ADDRESS,
        ID_State    = P_ID_STATE,
        ID_City     = P_ID_CITY,
        ZIP_Code    = P_ZIP_CODE,
        ID_Country  = P_ID_COUNTRY,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON,
        ID_Customer = P_ID_CUSTOMER
    WHERE Address_ID = P_ADDRESS_ID;
    COMMIT;
END MODIFICAR_FIDE_ADDRESS_TB_SP;
/

-- Procedimiento para desactivar ADDRESS
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_ADDRESS_TB_SP
(
    P_ADDRESS_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ADDRESS_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Address_ID = P_ADDRESS_ID;
    COMMIT;
END ELIMINAR_FIDE_ADDRESS_TB_SP;
/

 

-- Procedimiento para Insertar PRODUCT
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_PRODUCT_TB_SP
(
    P_PRODUCT_ID       IN NUMBER,
    P_DESCRIPTION      IN VARCHAR2,
    P_CATEGORY_TYPE_ID IN NUMBER,
    P_COMMENTS         IN VARCHAR2,
    P_UNIT_PRICE       IN NUMBER,
    P_IMAGE_PATH       IN VARCHAR2,
    P_STATUS_ID        IN NUMBER,
    P_CREATED_BY       IN VARCHAR2,
    P_CREATED_ON       IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_PRODUCT_TB
    (
        Product_ID,
        Description,
        Category_Type_ID,
        Comments,
        Unit_price,
        Image_path,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_PRODUCT_ID,
        P_DESCRIPTION,
        P_CATEGORY_TYPE_ID,
        P_COMMENTS,
        P_UNIT_PRICE,
        P_IMAGE_PATH,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_PRODUCT_TB_SP;
/

-- Procedimiento para Modificar PRODUCT
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_PRODUCT_TB_SP
(
    P_PRODUCT_ID       IN NUMBER,
    P_DESCRIPTION      IN VARCHAR2,
    P_CATEGORY_TYPE_ID IN NUMBER,
    P_COMMENTS         IN VARCHAR2,
    P_UNIT_PRICE       IN NUMBER,
    P_IMAGE_PATH       IN VARCHAR2,
    P_STATUS_ID        IN NUMBER,
    P_MODIFIED_BY      IN VARCHAR2,
    P_MODIFIED_ON      IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_PRODUCT_TB
    SET Description      = P_DESCRIPTION,
        Category_Type_ID = P_CATEGORY_TYPE_ID,
        Comments         = P_COMMENTS,
        Unit_price       = P_UNIT_PRICE,
        Image_path       = P_IMAGE_PATH,
        Status_ID        = P_STATUS_ID,
        Modified_By      = P_MODIFIED_BY,
        Modified_On      = P_MODIFIED_ON
    WHERE Product_ID = P_PRODUCT_ID;
    COMMIT;
END MODIFICAR_FIDE_PRODUCT_TB_SP;
/

-- Procedimiento para desactivar PRODUCT
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_PRODUCT_TB_SP
(
    P_PRODUCT_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_PRODUCT_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Product_ID = P_PRODUCT_ID;
    COMMIT;
END ELIMINAR_FIDE_PRODUCT_TB_SP;
/

 

-- Procedimiento para Insertar INVENTORY
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_INVENTORY_TB_SP
(
    P_INVENTORY_ID IN NUMBER,
    P_DESCRIPTION  IN VARCHAR2,
    P_STATUS_ID    IN NUMBER,
    P_CREATED_BY   IN VARCHAR2,
    P_CREATED_ON   IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_INVENTORY_TB
    (
        Inventory_ID,
        Description,
        Status_ID,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_INVENTORY_ID,
        P_DESCRIPTION,
        P_STATUS_ID,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_INVENTORY_TB_SP;
/

-- Procedimiento para Modificar INVENTORY
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_INVENTORY_TB_SP
(
    P_INVENTORY_ID IN NUMBER,
    P_DESCRIPTION  IN VARCHAR2,
    P_STATUS_ID    IN NUMBER,
    P_MODIFIED_BY  IN VARCHAR2,
    P_MODIFIED_ON  IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_INVENTORY_TB
    SET Description  = P_DESCRIPTION,
        Status_ID    = P_STATUS_ID,
        Modified_By  = P_MODIFIED_BY,
        Modified_On  = P_MODIFIED_ON
    WHERE Inventory_ID = P_INVENTORY_ID;
    COMMIT;
END MODIFICAR_FIDE_INVENTORY_TB_SP;
/

-- Procedimiento para desactivar INVENTORY
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_INVENTORY_TB_SP
(
    P_INVENTORY_ID IN NUMBER,
    P_MODIFIED_BY  IN VARCHAR2,
    P_MODIFIED_ON  IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_INVENTORY_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Inventory_ID = P_INVENTORY_ID;
    COMMIT;
END ELIMINAR_FIDE_INVENTORY_TB_SP;
/

 

-- Procedimiento para Insertar INVENTORY_LINES
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_INVENTORY_LINES_TB_SP
(
    P_INVENTORY_LINES_ID IN NUMBER,
    P_INVENTORY_ID       IN NUMBER,
    P_PRODUCT_ID         IN NUMBER,
    P_COMMENTS           IN VARCHAR2,
    P_QUANTITY_STOCKED   IN NUMBER,
    P_QUANTITY_RESERVED  IN NUMBER,
    P_STATUS_ID          IN NUMBER,
    P_LAST_RESTOCKED     IN TIMESTAMP,
    P_CREATED_BY         IN VARCHAR2,
    P_CREATED_ON         IN TIMESTAMP
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_INVENTORY_LINES_TB
    (
        Inventory_Lines_ID,
        Inventory_ID,
        Product_ID,
        Comments,
        Quantity_Stocked,
        Quantity_Reserved,
        Status_ID,
        Last_ReStocked,
        Created_By,
        Created_On
    )
    VALUES
    (
        P_INVENTORY_LINES_ID,
        P_INVENTORY_ID,
        P_PRODUCT_ID,
        P_COMMENTS,
        P_QUANTITY_STOCKED,
        P_QUANTITY_RESERVED,
        P_STATUS_ID,
        P_LAST_RESTOCKED,
        P_CREATED_BY,
        P_CREATED_ON
    );
    COMMIT;
END INSERTAR_FIDE_INVENTORY_LINES_TB_SP;
/

-- Procedimiento para Modificar INVENTORY_LINES
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_INVENTORY_LINES_TB_SP
(
    P_INVENTORY_LINES_ID IN NUMBER,
    P_INVENTORY_ID       IN NUMBER,
    P_PRODUCT_ID         IN NUMBER,
    P_COMMENTS           IN VARCHAR2,
    P_QUANTITY_STOCKED   IN NUMBER,
    P_QUANTITY_RESERVED  IN NUMBER,
    P_STATUS_ID          IN NUMBER,
    P_LAST_RESTOCKED     IN TIMESTAMP,
    P_MODIFIED_BY        IN VARCHAR2,
    P_MODIFIED_ON        IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_INVENTORY_LINES_TB
    SET Inventory_ID       = P_INVENTORY_ID,
        Product_ID         = P_PRODUCT_ID,
        Comments           = P_COMMENTS,
        Quantity_Stocked   = P_QUANTITY_STOCKED,
        Quantity_Reserved  = P_QUANTITY_RESERVED,
        Status_ID          = P_STATUS_ID,
        Last_ReStocked     = P_LAST_RESTOCKED,
        Modified_By        = P_MODIFIED_BY,
        Modified_On        = P_MODIFIED_ON
    WHERE Inventory_Lines_ID = P_INVENTORY_LINES_ID;
    COMMIT;
END MODIFICAR_FIDE_INVENTORY_LINES_TB_SP;
/

-- Procedimiento para desactivar INVENTORY_LINES
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_INVENTORY_LINES_TB_SP
(
    P_INVENTORY_LINES_ID IN NUMBER,
    P_MODIFIED_BY        IN VARCHAR2,
    P_MODIFIED_ON        IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_INVENTORY_LINES_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Inventory_Lines_ID = P_INVENTORY_LINES_ID;
    COMMIT;
END ELIMINAR_FIDE_INVENTORY_LINES_TB_SP;
/

 

-- Procedimiento para Insertar ORDER
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_ORDER_TB_SP
(
    P_ORDER_ID          IN NUMBER,
    P_CUSTOMER_ID       IN NUMBER,
    P_ORDER_DATE        IN TIMESTAMP,
    P_ORDER_AMOUNT      IN NUMBER,
    P_ORDER_TAX         IN NUMBER,
    P_COMMENTS          IN VARCHAR2,
    P_DISPATCH          IN NUMBER,
    P_FULLFIELD         IN NUMBER,
    P_STATUS_ID         IN NUMBER,
    P_PAYMENT_METHOD_ID IN NUMBER,
    P_CREATED_ON        IN TIMESTAMP,
    P_CREATED_BY        IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_ORDER_TB
    (
        Order_ID,
        Customer_ID,
        Order_Date,
        Order_Amount,
        Order_Tax,
        Comments,
        Dispatch,
        Fullfield,
        Status_ID,
        Payment_Method_ID,
        Created_On,
        Created_By
    )
    VALUES
    (
        P_ORDER_ID,
        P_CUSTOMER_ID,
        P_ORDER_DATE,
        P_ORDER_AMOUNT,
        P_ORDER_TAX,
        P_COMMENTS,
        P_DISPATCH,
        P_FULLFIELD,
        P_STATUS_ID,
        P_PAYMENT_METHOD_ID,
        P_CREATED_ON,
        P_CREATED_BY
    );
    COMMIT;
END INSERTAR_FIDE_ORDER_TB_SP;
/

-- Procedimiento para Modificar ORDER
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_ORDER_TB_SP
(
    P_ORDER_ID          IN NUMBER,
    P_CUSTOMER_ID       IN NUMBER,
    P_ORDER_DATE        IN TIMESTAMP,
    P_ORDER_AMOUNT      IN NUMBER,
    P_ORDER_TAX         IN NUMBER,
    P_COMMENTS          IN VARCHAR2,
    P_DISPATCH          IN NUMBER,
    P_FULLFIELD         IN NUMBER,
    P_STATUS_ID         IN NUMBER,
    P_PAYMENT_METHOD_ID IN NUMBER,
    P_MODIFIED_BY       IN VARCHAR2,
    P_MODIFIED_ON       IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ORDER_TB
    SET Customer_ID       = P_CUSTOMER_ID,
        Order_Date        = P_ORDER_DATE,
        Order_Amount      = P_ORDER_AMOUNT,
        Order_Tax         = P_ORDER_TAX,
        Comments          = P_COMMENTS,
        Dispatch          = P_DISPATCH,
        Fullfield         = P_FULLFIELD,
        Status_ID         = P_STATUS_ID,
        Payment_Method_ID = P_PAYMENT_METHOD_ID,
        Modified_By       = P_MODIFIED_BY,
        Modified_On       = P_MODIFIED_ON
    WHERE Order_ID = P_ORDER_ID;
    COMMIT;
END MODIFICAR_FIDE_ORDER_TB_SP;
/

-- Procedimiento para desactivar ORDER
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_ORDER_TB_SP
(
    P_ORDER_ID    IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ORDER_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Order_ID = P_ORDER_ID;
    COMMIT;
END ELIMINAR_FIDE_ORDER_TB_SP;
/

 
-- Procedimiento para Insertar ORDER_LINES
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_ORDER_LINES_TB_SP
(
    P_ORDER_LINE_ID IN NUMBER,
    P_ORDER_ID      IN NUMBER,
    P_PRODUCT_ID    IN NUMBER,
    P_QTY_ITEM      IN NUMBER,
    P_COMMENTS      IN VARCHAR2,
    P_STATUS_ID     IN NUMBER,
    P_TOTAL_PRICE   IN NUMBER,
    P_CREATED_ON    IN TIMESTAMP,
    P_CREATED_BY    IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_ORDER_LINES_TB
    (
        Order_Line_ID,
        Order_ID,
        Product_ID,
        Qty_Item,
        Comments,
        Status_ID,
        Total_Price,
        Created_On,
        Created_By
    )
    VALUES
    (
        P_ORDER_LINE_ID,
        P_ORDER_ID,
        P_PRODUCT_ID,
        P_QTY_ITEM,
        P_COMMENTS,
        P_STATUS_ID,
        P_TOTAL_PRICE,
        P_CREATED_ON,
        P_CREATED_BY
    );
    COMMIT;
END INSERTAR_FIDE_ORDER_LINES_TB_SP;
/

-- Procedimiento para Modificar ORDER_LINES
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_ORDER_LINES_TB_SP
(
    P_ORDER_LINE_ID IN NUMBER,
    P_ORDER_ID      IN NUMBER,
    P_PRODUCT_ID    IN NUMBER,
    P_QTY_ITEM      IN NUMBER,
    P_COMMENTS      IN VARCHAR2,
    P_STATUS_ID     IN NUMBER,
    P_TOTAL_PRICE   IN NUMBER,
    P_MODIFIED_BY   IN VARCHAR2,
    P_MODIFIED_ON   IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ORDER_LINES_TB
    SET Order_ID    = P_ORDER_ID,
        Product_ID  = P_PRODUCT_ID,
        Qty_Item    = P_QTY_ITEM,
        Comments    = P_COMMENTS,
        Status_ID   = P_STATUS_ID,
        Total_Price = P_TOTAL_PRICE,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Order_Line_ID = P_ORDER_LINE_ID;
    COMMIT;
END MODIFICAR_FIDE_ORDER_LINES_TB_SP;
/

-- Procedimiento para desactivar ORDER_LINES
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_ORDER_LINES_TB_SP
(
    P_ORDER_LINE_ID IN NUMBER,
    P_MODIFIED_BY   IN VARCHAR2,
    P_MODIFIED_ON   IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_ORDER_LINES_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Order_Line_ID = P_ORDER_LINE_ID;
    COMMIT;
END ELIMINAR_FIDE_ORDER_LINES_TB_SP;
/

 
-- Procedimiento para Insertar BILLING
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_BILLING_TB_SP
(
    P_BILLING_ID         IN NUMBER,
    P_ORDER_ID           IN NUMBER,
    P_CUSTOMER_ID        IN NUMBER,
    P_INVOICED_ADDRESS_ID IN NUMBER,
    P_BILLING_DATE       IN TIMESTAMP,
    P_TOTAL_AMOUNT       IN NUMBER,
    P_COMMENTS           IN VARCHAR2,
    P_STATUS_ID          IN NUMBER,
    P_PAYMENT_METHOD_ID  IN NUMBER,
    P_CREATED_ON         IN TIMESTAMP,
    P_CREATED_BY         IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_BILLING_TB
    (
        Billing_ID,
        Order_ID,
        Customer_ID,
        Invoiced_Address_ID,
        Billing_Date,
        Total_Amount,
        Comments,
        Status_ID,
        Payment_Method_ID,
        Created_On,
        Created_By
    )
    VALUES
    (
        P_BILLING_ID,
        P_ORDER_ID,
        P_CUSTOMER_ID,
        P_INVOICED_ADDRESS_ID,
        P_BILLING_DATE,
        P_TOTAL_AMOUNT,
        P_COMMENTS,
        P_STATUS_ID,
        P_PAYMENT_METHOD_ID,
        P_CREATED_ON,
        P_CREATED_BY
    );
    COMMIT;
END INSERTAR_FIDE_BILLING_TB_SP;
/

-- Procedimiento para Modificar BILLING
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_BILLING_TB_SP
(
    P_BILLING_ID         IN NUMBER,
    P_ORDER_ID           IN NUMBER,
    P_CUSTOMER_ID        IN NUMBER,
    P_INVOICED_ADDRESS_ID IN NUMBER,
    P_BILLING_DATE       IN TIMESTAMP,
    P_TOTAL_AMOUNT       IN NUMBER,
    P_COMMENTS           IN VARCHAR2,
    P_STATUS_ID          IN NUMBER,
    P_PAYMENT_METHOD_ID  IN NUMBER,
    P_MODIFIED_BY        IN VARCHAR2,
    P_MODIFIED_ON        IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_BILLING_TB
    SET Order_ID           = P_ORDER_ID,
        Customer_ID        = P_CUSTOMER_ID,
        Invoiced_Address_ID = P_INVOICED_ADDRESS_ID,
        Billing_Date       = P_BILLING_DATE,
        Total_Amount       = P_TOTAL_AMOUNT,
        Comments           = P_COMMENTS,
        Status_ID          = P_STATUS_ID,
        Payment_Method_ID  = P_PAYMENT_METHOD_ID,
        Modified_By        = P_MODIFIED_BY,
        Modified_On        = P_MODIFIED_ON
    WHERE Billing_ID = P_BILLING_ID;
    COMMIT;
END MODIFICAR_FIDE_BILLING_TB_SP;
/

-- Procedimiento para desactivar BILLING
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_BILLING_TB_SP
(
    P_BILLING_ID IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_BILLING_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Billing_ID = P_BILLING_ID;
    COMMIT;
END ELIMINAR_FIDE_BILLING_TB_SP;
/

 
-- Procedimiento para Insertar CART
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_CART_TB_SP
(
    P_CART_ID           IN NUMBER,
    P_CUSTOMER_ID       IN NUMBER,
    P_ADDRESS_ID        IN NUMBER,
    P_ORDER_DATE        IN TIMESTAMP,
    P_COMMENTS          IN VARCHAR2,
    P_STATUS_ID         IN NUMBER,
    P_PAYMENT_METHOD_ID IN NUMBER,
    P_CREATED_ON        IN TIMESTAMP,
    P_CREATED_BY        IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_CART_TB
    (
        Cart_ID,
        Customer_ID,
        Address_ID,
        Order_Date,
        Comments,
        Status_ID,
        Payment_Method_ID,
        Created_On,
        Created_By
    )
    VALUES
    (
        P_CART_ID,
        P_CUSTOMER_ID,
        P_ADDRESS_ID,
        P_ORDER_DATE,
        P_COMMENTS,
        P_STATUS_ID,
        P_PAYMENT_METHOD_ID,
        P_CREATED_ON,
        P_CREATED_BY
    );
    COMMIT;
END INSERTAR_FIDE_CART_TB_SP;
/

-- Procedimiento para Modificar CART
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_CART_TB_SP
(
    P_CART_ID           IN NUMBER,
    P_CUSTOMER_ID       IN NUMBER,
    P_ADDRESS_ID        IN NUMBER,
    P_ORDER_DATE        IN TIMESTAMP,
    P_COMMENTS          IN VARCHAR2,
    P_STATUS_ID         IN NUMBER,
    P_PAYMENT_METHOD_ID IN NUMBER,
    P_MODIFIED_BY       IN VARCHAR2,
    P_MODIFIED_ON       IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CART_TB
    SET Customer_ID       = P_CUSTOMER_ID,
        Address_ID        = P_ADDRESS_ID,
        Order_Date        = P_ORDER_DATE,
        Comments          = P_COMMENTS,
        Status_ID         = P_STATUS_ID,
        Payment_Method_ID = P_PAYMENT_METHOD_ID,
        Modified_By       = P_MODIFIED_BY,
        Modified_On       = P_MODIFIED_ON
    WHERE Cart_ID = P_CART_ID;
    COMMIT;
END MODIFICAR_FIDE_CART_TB_SP;
/

-- Procedimiento para desactivar CART
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_CART_TB_SP
(
    P_CART_ID    IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CART_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Cart_ID = P_CART_ID;
    COMMIT;
END ELIMINAR_FIDE_CART_TB_SP;
/

 

-- Procedimiento para Insertar CART_LINES
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_CART_LINES_TB_SP
(
    P_CART_LINE_ID IN NUMBER,
    P_CART_ID      IN NUMBER,
    P_PRODUCT_ID   IN NUMBER,
    P_QTY_ITEM     IN NUMBER,
    P_COMMENTS     IN VARCHAR2,
    P_STATUS_ID    IN NUMBER,
    P_TOTAL_PRICE  IN NUMBER,
    P_CREATED_ON   IN TIMESTAMP,
    P_CREATED_BY   IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_CART_LINES_TB
    (
        Cart_Line_ID,
        Cart_ID,
        Product_ID,
        Qty_Item,
        Comments,
        Status_ID,
        Total_Price,
        Created_On,
        Created_By
    )
    VALUES
    (
        P_CART_LINE_ID,
        P_CART_ID,
        P_PRODUCT_ID,
        P_QTY_ITEM,
        P_COMMENTS,
        P_STATUS_ID,
        P_TOTAL_PRICE,
        P_CREATED_ON,
        P_CREATED_BY
    );
    COMMIT;
END INSERTAR_FIDE_CART_LINES_TB_SP;
/

-- Procedimiento para Modificar CART_LINES
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_CART_LINES_TB_SP
(
    P_CART_LINE_ID IN NUMBER,
    P_CART_ID      IN NUMBER,
    P_PRODUCT_ID   IN NUMBER,
    P_QTY_ITEM     IN NUMBER,
    P_COMMENTS     IN VARCHAR2,
    P_STATUS_ID    IN NUMBER,
    P_TOTAL_PRICE  IN NUMBER,
    P_MODIFIED_BY  IN VARCHAR2,
    P_MODIFIED_ON  IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CART_LINES_TB
    SET Cart_ID     = P_CART_ID,
        Product_ID  = P_PRODUCT_ID,
        Qty_Item    = P_QTY_ITEM,
        Comments    = P_COMMENTS,
        Status_ID   = P_STATUS_ID,
        Total_Price = P_TOTAL_PRICE,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Cart_Line_ID = P_CART_LINE_ID;
    COMMIT;
END MODIFICAR_FIDE_CART_LINES_TB_SP;
/

-- Procedimiento para desactivar CART_LINES
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_CART_LINES_TB_SP
(
    P_CART_LINE_ID IN NUMBER,
    P_MODIFIED_BY  IN VARCHAR2,
    P_MODIFIED_ON  IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_CART_LINES_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Cart_Line_ID = P_CART_LINE_ID;
    COMMIT;
END ELIMINAR_FIDE_CART_LINES_TB_SP;
/

 

-- Procedimiento para Insertar SPECIAL_ORDER
CREATE OR REPLACE PROCEDURE INSERTAR_FIDE_SPECIAL_ORDER_TB_SP
(
    P_ORDER_ID    IN NUMBER,
    P_CUSTOMER_ID IN NUMBER,
    P_ORDER_DATE  IN TIMESTAMP,
    P_ORDER_QTY   IN NUMBER,
    P_COMMENTS    IN VARCHAR2,
    P_STATUS_ID   IN NUMBER,
    P_CREATED_ON  IN TIMESTAMP,
    P_CREATED_BY  IN VARCHAR2
)
IS
BEGIN
    INSERT INTO FIDE_SAMDESIGN.FIDE_SPECIAL_ORDER_TB
    (
        Order_ID,
        Customer_ID,
        Order_Date,
        Order_Qty,
        Comments,
        Status_ID,
        Created_On,
        Created_By
    )
    VALUES
    (
        P_ORDER_ID,
        P_CUSTOMER_ID,
        P_ORDER_DATE,
        P_ORDER_QTY,
        P_COMMENTS,
        P_STATUS_ID,
        P_CREATED_ON,
        P_CREATED_BY
    );
    COMMIT;
END INSERTAR_FIDE_SPECIAL_ORDER_TB_SP;
/

-- Procedimiento para Modificar SPECIAL_ORDER
CREATE OR REPLACE PROCEDURE MODIFICAR_FIDE_SPECIAL_ORDER_TB_SP
(
    P_ORDER_ID    IN NUMBER,
    P_CUSTOMER_ID IN NUMBER,
    P_ORDER_DATE  IN TIMESTAMP,
    P_ORDER_QTY   IN NUMBER,
    P_COMMENTS    IN VARCHAR2,
    P_STATUS_ID   IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_SPECIAL_ORDER_TB
    SET Customer_ID = P_CUSTOMER_ID,
        Order_Date  = P_ORDER_DATE,
        Order_Qty   = P_ORDER_QTY,
        Comments    = P_COMMENTS,
        Status_ID   = P_STATUS_ID,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Order_ID = P_ORDER_ID;
    COMMIT;
END MODIFICAR_FIDE_SPECIAL_ORDER_TB_SP;
/

-- Procedimiento para desactivar SPECIAL_ORDER
CREATE OR REPLACE PROCEDURE ELIMINAR_FIDE_SPECIAL_ORDER_TB_SP
(
    P_ORDER_ID    IN NUMBER,
    P_MODIFIED_BY IN VARCHAR2,
    P_MODIFIED_ON IN TIMESTAMP
)
IS
BEGIN
    UPDATE FIDE_SAMDESIGN.FIDE_SPECIAL_ORDER_TB
    SET Status_ID   = 0,
        Modified_By = P_MODIFIED_BY,
        Modified_On = P_MODIFIED_ON
    WHERE Order_ID = P_ORDER_ID;
    COMMIT;
END ELIMINAR_FIDE_SPECIAL_ORDER_TB_SP;
/

